language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
script:
  - yarn run test:prod && yarn run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
